name: lint
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Awesome_Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx awesome-lint
